### PR TITLE
Noarch build of v3.1.1

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Hello @minrk, @ocepaf, @nehaljwani, @bollwyvl,

I could really use a noarch build of v3.1.1. The [current builds for v3.1.1](https://anaconda.org/conda-forge/jsonschema/files?version=3.1.1) max out at Python 3.8.

I created this as a **draft** PR simply to reduce the chance that this accidentally gets merged into `master`. (Evidently unnecessary here in this case since you're all conda-forge legends...) I would like to create a `v3.1.1` branch, but I'm not a maintainer. I was hoping that one of you could merge this into a `v3.1.1` branch for me. Thanks so much!

**Comment by bollwyvl** [comment]
We can take a look at starting a `3.x` line... though it looks like `3.2` is the last of that. Is there a specific reason that "latest of major" won't work for you use cases? I was somewhat dubious of landing the `noarch` until we had at least tested it, and might be the same on no doing historical patches for stuff that was working fine..

**Comment by maresb** [comment]
Thanks @bollwyvl for the quick response! I'm trying to install `dbt-core` with a pin on `python=3.9.*`.

```
dbt-core-0.21.0-pyhd8ed1ab_2 requires hologram 0.0.14
hologram-0.0.14-pyhd8ed1ab_0 requires jsonschema <3.2,>=3.0
jsonschema-3.1.1-py38_0 requires python >=3.8,<3.9.0a0
```

**Comment by bollwyvl** [comment]
Indeed. I guess we'd want to start a `3.1.x` branch, then, at #22  b3d9c63144e9cebb75981ed88cf02d1b813fb6e3 and then target that with this pr... not sure if we can noarch that version, though...

**Comment by maresb** [comment]
@bollwyvl, why couldn't we noarch it? It looks to me like the only thing preventing noarch is the `py27` support. I'll rebase on the indicated commit and open a new PR...

**Comment by bollwyvl** [comment]
Branch up: https://github.com/conda-forge/jsonschema-feedstock/tree/3.1.x

> why couldn't we noarch it

Because I'm both lazy and conservative about historical packages... I'd ask we at least keep the tests running, as we might end up with something that _can't_ be installed with a newer python etc. No doubt nobody upstream isn't testing historical versions.

**Pull request closed without merging**
