### PR TITLE
Noarch build of v3.1.1

### PR DESCRIPTION
**Pull request by maresb**
Replaces #37

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
Attn: @bollwyvl

**Comment by maresb** [comment]
How do we do this? Can you open a branch on b3d9c63 so that I can retarget this PR?

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
In the other PR, @bollwyvl said:
> I'd ask we at least keep the tests running, as we might end up with something that can't be installed with a newer python etc.

What do you have in mind for tests? Do you want to get the pytest suite running?

**Comment by maresb** [comment]
@bollwyvl, is this now ready to go? I implemented pytest and coverage like in the head of master.

By the way, what on earth is the point of running coverage tests on conda-forge??? In order to get the tests to pass, I had to lower the coverage threshold from 93% to 92% on the test command.

**Comment by maresb** [comment]
@bollwyvl, any further thoughts? Does this PR meet your expectations?

**Review by bollwyvl — APPROVED** [review]
LGTM!

**Pull request merged**
